### ISSUE TITLE
Impossible to run the module

### ISSUE THREAD

**Issue by maxencekyz** [nigel-daniels/MMM-VTA-Live#1]
Hello @nigel-daniels ,

I settled everything good. No issue during installation.
I put the api, station ID, etc..
And this is what I have on my Magic Mirror :
![image](https://user-images.githubusercontent.com/80335419/110934137-ec877780-832d-11eb-8369-001155e35dcc.png)

It do not show anything anymore.
FYI, this is the only module that I've got with clock. And by removing yours, everything works fine.
I've also installed many others transportation modules in the past, so i know how it works on API and station ID.
So sad..

Any issue ?
Kind regards,
- Max

**Comment by nigel-daniels** [comment]
Hi Max, to help diagnose the issue please can you post you configuration (without personal keys) I can try recreating the issue. Thx.

**Comment by maxencekyz** [comment]
Sure!

Here we go :

> { 
			module:    'MMM-VTA-Live',
			position:  'bottom_left',
			header:    'VTA Rail Arrivals',
			config:	 {
						api_key:   'xxxxxxxxxxxxxxxxxxx', 
						agency:		'SC',
						stop_code:   '8040224',  
						stop_name: 'St James Station',
						interval:  60000 //1 minute
						}
		},

**Comment by nigel-daniels** [comment]
Apologies, that was an old example of what the config should look like, the config format is valid but  the stop_code was for the old TransLoc API.  This config will not return any data, although in my tests this displayed the module but with no data. I did not get a 'site not accessible' message.  That suggests you have a different problem outside of this module.  

Given the you get a message that the site is inaccessible check two things: 
1) you are able to access 511.org from your network, I recommend calling their API with your api_key e.g. see if you get data when you run 
`http://api.511.org/transit/gtfsoperators?api_key=xxxxxxxxxxxxxxxxxxxx`
2) Check your api_key is valid.

BTW I've update the documentation to use the current 511.org API stop_code and added advice on how to get a current stop code from the 511.org API.

**Comment by maxencekyz** [comment]
Thank you @nigel-daniels 
Working like a charm!
However, you made a mistake in your tutorial example.
The stop_code ID ( 64749 ) corresponds to St James (South), not North.

Thank you again for everything,
God bless you,

- Max
